### PR TITLE
Add bob.ip.facedetect

### PR DESCRIPTION
**Pull request by patricksnape**
Thin wrapper around `bob.ip.facedetect` - not including training.

Currently not a conda dependency as bob only exists on conda-forge at the moment.

### CODE REVIEW

**Comment by patricksnape** [comment]
Umm... coveralls... Who invited you?

**Comment by jabooth** [comment]
@patricksnape look at this guy, crawling out of the woodwork...what is going on?

**Comment by patricksnape** [comment]
@coveralls You can take your silly outfit and get out of my PR.

**Comment by patricksnape** [comment]
Ignore Appveyor because I removed it.

**Comment by patricksnape** [comment]
@jabooth Please review.

**Pull request merged**
